---
- name: test win_command
  hosts: all
 
  tasks:
 
  - name: run powershell
    win_command: powershell.exe
    args:
      stdin: ls
    register: shellresults
       
  - name: setting fact Debian lighttpd
    set_fact:
      shell_info: "www-data"
