---
- name: test win_command
  hosts: all
 
  tasks:
 
  - name: run powershell
    win_command: powershell.exe
    register: results
    args:
      stdin: ls
  
  - name: process win_shell output
    set_fact:
      info: "{{ results.stdout | from_json }}"

  - name: show results
    debug:
      msg: results {{ info }}
