---
- name: test win_command
  hosts: all
 
  tasks:
 
  - name: Run an executable and send data to the stdin for the executable
    win_command: powershell.exe
    register: stdout_lines
    args:
      stdin: ls
