---
- name: test win_command
  hosts: all
 
  tasks:
 
  - name: run powershell
    win_command: powershell.exe
    args:
      stdin: ls
    register: shellresults
       
  - name: setting fact shell_info
    set_fact:
      shell_info: "{{ shellresults.stdout | from_json }}"
