---
- name: test win_command
  hosts: all
 
  tasks:
 
  - name: run powershell
    win_command: powershell.exe
    register: shellresults
    args:
      stdin: ls
  
  - name: process win_shell output
    set_fact:
      queryinfo: "{{ shellresults.stdout | from_json }}"

  - name: show results
    debug:
      msg: shellresults {{ queryinfo }}
