---
- name: test win_command
  hosts: all
 
  tasks:
 
  - name: run powershell
    win_command: powershell.exe
    args:
      stdin: ls
    register: shellresults
  
  - name: Process win_shell output
    set_fact:
      shellinfo: "{{ shellresults.stdout | from_json }}"
